inherit_from: ../.rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Encoding:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Max: 99